# Generated by Django 5.2 on 2025-09-08 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Impresion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.BooleanField()),
                ('formato', models.CharField(choices=[('A0', 'A0 (841 × 1189 mm)'), ('A1', 'A1 (594 × 841 mm)'), ('A2', 'A2 (420 × 594 mm)'), ('A3', 'A3 (297 × 420 mm)'), ('A4', 'A4 (210 × 297 mm)'), ('A5', 'A5 (148 × 210 mm)'), ('A6', 'A6 (105 × 148 mm)')], default='A4', max_length=3)),
                ('url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('En revisión', 'en revisión'), ('En proceso', 'en proceso'), ('Preparado', 'preparado'), ('Retirado', 'retirado'), ('Cancelado', 'cancelado')], default='En revisión', max_length=100)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precioUnitario', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=128)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Pendiente', 'pendiente'), ('Completado', 'completado'), ('Fallido', 'fallido')], default='Pendiente', max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('metodoPago', models.CharField(choices=[('Crédito', 'crédito'), ('Transferencia', 'transferencia'), ('Débito', 'débito'), ('Efectivo', 'efectivo')], default='Efectivo', max_length=15)),
                ('monto', models.FloatField()),
                ('fk_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoImpresionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.FloatField()),
                ('cantidadCopias', models.IntegerField()),
                ('fk_impresion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.impresion')),
                ('fk_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoProductoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.FloatField()),
                ('cantidad', models.IntegerField()),
                ('fk_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pedido')),
                ('fk_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='fk_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuarioTipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuariotipo'),
        ),
    ]
