# Generated by Django 5.2.7 on 2025-10-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impresion',
            name='url',
            field=models.ImageField(upload_to='archivos/'),
        ),
    ]
