# Generated by Django 5.2.4 on 2026-02-02 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_impresion_url'),
        ('app', '0004_usuario_activo_usuario_created_at_usuario_updated_at'),
    ]

    operations = [
    ]
