# Generated by Django 5.2.4 on 2026-02-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_merge_20260202_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariotipo',
            old_name='descripcio',
            new_name='descripcion',
        ),
        migrations.AlterField(
            model_name='impresion',
            name='url',
            field=models.CharField(max_length=300),
        ),
    ]
