# Generated by Django 5.2.11 on 2026-02-05 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_pedido_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='usuariotipo',
            name='descuento',
            field=models.IntegerField(default=0, help_text='Porcentaje de descuento (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
