# Generated by Django 6.0.1 on 2026-02-06 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_producto_options_usuariotipo_descuento'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoEstadoHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('En revisión', 'en revisión'), ('En proceso', 'en proceso'), ('Preparado', 'preparado'), ('Retirado', 'retirado'), ('Cancelado', 'cancelado')], max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fk_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='app.pedido')),
            ],
            options={
                'verbose_name': 'Historial de estado de pedido',
                'verbose_name_plural': 'Historial de estados de pedidos',
                'ordering': ['fecha'],
            },
        ),
    ]
