# Generated by Django 5.2.11 on 2026-02-06 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_pedido_estado_historial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('ECONOMICO', 'Movimiento Económico'), ('OPERATIVO', 'Cantidad de Pedidos'), ('DESCUENTOS', 'Resumen de Descuentos Aplicados')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='reportes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fk_usuario_creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.usuario')),
            ],
        ),
    ]
