# Generated by Django 5.2.11 on 2026-02-06 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_reporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='archivo',
        ),
    ]
