# Generated by Django 5.2.11 on 2026-02-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_reporte_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='datos_reporte',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
