# Generated by Django 5.2 on 2026-02-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_remove_reporte_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="impresion",
            name="archivo",
            field=models.FileField(blank=True, null=True, upload_to="impresiones/"),
        ),
    ]
