# Generated by Django 6.0.1 on 2026-02-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_en_revision_a_pendiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='motivo_correccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'pendiente'), ('En proceso', 'en proceso'), ('Preparado', 'preparado'), ('Retirado', 'retirado'), ('Cancelado', 'cancelado'), ('Requiere Corrección', 'requiere corrección')], default='Pendiente', max_length=100),
        ),
        migrations.AlterField(
            model_name='pedidoestadohistorial',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'pendiente'), ('En proceso', 'en proceso'), ('Preparado', 'preparado'), ('Retirado', 'retirado'), ('Cancelado', 'cancelado'), ('Requiere Corrección', 'requiere corrección')], max_length=100),
        ),
    ]
