# Generated by Django 6.0.1 on 2026-02-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_pedido_motivo_correccion_alter_pedido_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoImpresion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato', models.CharField(choices=[('A0', 'A0 (841 × 1189 mm)'), ('A1', 'A1 (594 × 841 mm)'), ('A2', 'A2 (420 × 594 mm)'), ('A3', 'A3 (297 × 420 mm)'), ('A4', 'A4 (210 × 297 mm)'), ('A5', 'A5 (148 × 210 mm)'), ('A6', 'A6 (105 × 148 mm)')], max_length=3)),
                ('color', models.BooleanField()),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField()),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Impresión',
                'verbose_name_plural': 'Tipos de Impresión',
                'ordering': ['formato', 'color'],
            },
        ),
    ]
